In [14]:
A = "a"
a = 1

print A
print a

a
1


a = 3.111111111111111111111
print type(a)
a = "13.111111111111111111111"
print type(a)
a = 311111
print type(a)

a = 12
12 = a

In [24]:
a = 12
b = "hello"
print a
print b 

print "-------------------"

b = a 
print a
print b
print "-----------------------"

#b와 a같 묶여서 가진않는다
a= 98
print a
print b

12
hello
-------------------
12
12
-----------------------
98
12


In [25]:
a = "abcd"
a = a + "abcd"
print a

abcdabcd


In [44]:
a =  """Hello."What!!"  """
print a

Hello."What!!"  


In [34]:
a_list = [1,2,34,"abcd"]
print a_list

[1, 2, 34, 'abcd']


In [38]:
a_list.append("a")
print a_list

[1, 2, 34, 'abcd', 'a', 'a', 'a', 'a']


In [39]:
a_list.append("a")
print a_list

[1, 2, 34, 'abcd', 'a', 'a', 'a', 'a', 'a']


In [42]:
print a_list
a_list.insert(2,"b")
print a_list

[1, 2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a', 'a']
[1, 2, 'b', 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a', 'a']


In [43]:
print a_list
a_list.pop(3)
print a_list

[1, 2, 'b', 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a', 'a']
[1, 2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a', 'a']


In [48]:
print a_list
a_list.remove(1)
print a_list

[2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a']


ValueError: list.remove(x): x not in list

In [47]:
print a_list
a_list.remove("a")
print a_list

[2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a', 'a']
[2, 'b', 'b', 34, 'abcd', 'a', 'a', 'a']


In [50]:
d1 = {"a":1234,"b":5678}

In [52]:
d1.keys() #리스트형태로 반환해줌

['a', 'b']

In [53]:
d1.values()

[1234, 5678]

In [54]:
d1["a"]

1234

In [59]:
a = 2
if a>0:
    print "a는 양수"
elif a == 0:
    print "a는 0"
else:
    print "a는 음수"
        

a는 양수


range(0,10)

In [60]:
range(0,10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
for i in range(0,10,2):
    print i

0
2
4
6
8


In [91]:
a = [12,34,56]
for i in a:
    print i

12
34
56


In [90]:
a = ["a","b","c","d","e","f","g","c","i"]
b = []
for i in range(0,len(a)):
    if a[i] != "c":
        b.append(a[i])
print b

['a', 'b', 'd', 'e', 'f', 'g', 'i']


In [125]:
a = [["a","b","c","d"],"f","g",["c","i"]]
b = []

                   

for i in a:
    print type(i)
    if type(i)== type([]):
        for j in i:
            print j
            if j != "c":
                b.append(j)
            else:
                pass
    else:
        if(i != "c"):
            b.append(i)
        else:
            pass
            
print b



for i in range(0,len(a)):
    for j in range(0,len(a[i])):
        print a[i]
        print a[i][j]
        print "------------"
        if a[i][j] != "c":
            b.append(a[i][j])
print b
                

<type 'list'>
a
b
c
d
<type 'str'>
<type 'str'>
<type 'list'>
c
i
['a', 'b', 'd', 'f', 'g', 'i']
['a', 'b', 'c', 'd']
a
------------
['a', 'b', 'c', 'd']
b
------------
['a', 'b', 'c', 'd']
c
------------
['a', 'b', 'c', 'd']
d
------------
f
f
------------
g
g
------------
['c', 'i']
c
------------
['c', 'i']
i
------------
['a', 'b', 'd', 'f', 'g', 'i', 'a', 'b', 'd', 'f', 'g', 'i']


In [130]:
def sum2(a,b):
    result = a + b
    return result

In [126]:
10+30

40

In [131]:
sum2(10,30)

40

In [132]:
def noinput():
    result = "Hello!!!"
    return result

In [135]:
a = noinput()
print a

Hello!!


In [136]:
def noreturn(a,b):
    temp = a + b
    print "Hello Python + :" + str(temp)

In [140]:
a = noreturn(2,3)
print a

Hello Python + :5
None


In [143]:
def noinreturn():
    print "hello!~~~~~"

In [144]:
a = noinreturn()
print a
print "-------"
noinreturn()

hello!~~~~~
None
-------
hello!~~~~~


In [146]:
def sumrandom(*args):
    result = 0
    for i in args:
        result = result + i
    return result
    

In [150]:
print sumrandom(1,2,2,3,423,4324,234234,23,32)
print sumrandom(31,321,321,54325,435,43,423)

239044
55899


In [ ]:
myfunction("sum",10,20,30,40) --> 10+20+30+40
myfunction("count",1,2,3,4,5,6,7) --> 7
myfunction("ffffff",1,2,3,4,5,6,7)  --> 지정되지않았습니다. - 경고문

In [153]:
def myfunction(func,*args):
    if func == "sum":
        result = 0
        for i in args:
            result = result + i
        return result
    elif func == "count":
        return len(args)
    else:
        return "check for your function parameter!!!"

In [154]:
a = myfunction("sum",10,20,30,40)
print a 
a = myfunction("count",1,2,3,4,5,6,7)
print a 
a = myfunction("ffffff",1,2,3,4,5,6,7)
print a

100
7
check for your function parameter!!!


In [155]:
def multifunc(a,b):
    return a+b, a-b, a*b, a/b , a+b+3

In [156]:
multifunc(10,30) --> 리턴값이 듀블 쓰는건 리스트랑 같음ㅇㅇ

(40, -20, 300, 0, 43)

In [ ]:
def sum2(a,b):
    result = a + b
    return result
sum2(10,20)

In [157]:
(lambda x,y:x+y)(10,30)

40

In [165]:
def myfunc(func,*args):
    if func == "sel1":
        sumresult = 0
        dexresult = 1
        for i in args:
            sumresult = sumresult + i
            dexresult = dexresult * i
        return sumresult,dexresult
    elif func == "sel2":
        return args[0],args[len(args)-1]
    else:
        return "이상해요~~에러메세지"

            

In [166]:
print myfunc("sel1",1,2,3,4,5)
print myfunc("sel2",1,2,3,4,5)
print myfunc("aaaa",1,2,3,4,5)

(15, 120)
(1, 5)
이상해요~~에러메세지


In [168]:
import numpy as np

In [172]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

data3 = [[1,2,3,4],[5,6,7,8]]
arr3 = np.array(data3)

In [174]:
print arr1
print arr1.ndim
print arr1.shape
print arr1.dtype

print arr3
print arr3.ndim
print arr3.shape
print arr3.dtype

[ 6.   7.5  8.   0.   1. ]
1
(5L,)
float64
[[1 2 3 4]
 [5 6 7 8]]
2
(2L, 4L)
int32


In [178]:
#자료형 바꾸는방법
arr1 = np.array([1,2,3],dtype = np.float64)
arr2 = np.array([1,2,3],dtype = np.int8)
arr3 = np.array([1,2,3],dtype = np.string_)

print arr1
print arr2
print arr3

#변경수행 함수 astype
arr3 = arr3.astype(np.float64)
print arr3


[ 1.  2.  3.]
[1 2 3]
['1' '2' '3']
[ 1.  2.  3.]


In [ ]:
#배열 스칼라간 연산.
